#!/bin/sh

# $Id$
# part of m0n0wall (http://m0n0.ch/wall)
#
# Copyright (C) 2003-2005 Manuel Kasper <mk@neon1.net>.
# All rights reserved.

stty status '^T'

trap : 2
trap : 3

HOME=/
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export HOME PATH

set -T
trap "echo 'Reboot interrupted'; exit 1" 3

# make some directories in /var
mkdir /var/etc /var/db /var/empty

# generate circular logfiles
clog -i -s 262144 /var/log/system.log
clog -i -s 262144 /var/log/pbx.log
clog -i -s 262144 /var/log/cdr.log
chmod 0600 /var/log/*.log

adjkerntz -i

# Create an initial utmp file
cd /var/run && cp /dev/null utmp && chmod 644 utmp

# Run ldconfig
/sbin/ldconfig -elf /usr/lib /usr/local/lib

# let the PHP-based configuration subsystem set up the system now
/etc/rc.bootup


exit 0
