obj-m += auerask_cp3ks0.o ../auerask_cp3k_spi.o

EXTRA_CFLAGS += -I$(src)/.. -Wno-undef

auerask_cp3ks0-objs := auerask_cp3ks0_main.o ../auerask_cp3k_spi.o

.PHONY: $(src)/auerask_config.h

$(src)/auerask_config.h:
	echo "#ifndef __AUERASK_CONFIG_H__" > $(src)/auerask_config.h 
	echo "#define __AUERASK_CONFIG_H__" >> $(src)/auerask_config.h 
	echo >> $(src)/auerask_config.h
	echo "#define AUERASK_COMPILETIME $$(date +%s) // $$(date)" >> $(src)/auerask_config.h 
	echo "#define AUERASK_BUILDHOST \"$$(hostname)\"" >> $(src)/auerask_config.h
	echo >> $(src)/auerask_config.h
	echo "#endif" >> $(src)/auerask_config.h 

$(obj)/auerask_cp3ks0_main.o: $(src)/auerask_cp3ks0.h $(src)/../auerask_cp3k_spi.o

