--- dahdi-linux-2.2.0/Makefile.orig	2009-05-12 23:57:44.000000000 +0200
+++ dahdi-linux-2.2.0/Makefile	2009-12-10 16:55:11.000000000 +0100
@@ -7,7 +7,8 @@
 
 PWD:=$(shell pwd)
 
-DAHDI_MODULES_EXTRA:=$(MODULES_EXTRA:%=%.o) $(SUBDIRS_EXTRA:%=%/)
+#DAHDI_MODULES_EXTRA:=$(MODULES_EXTRA:%=%.o) $(SUBDIRS_EXTRA:%=%/)
+DAHDI_MODULES_EXTRA:=auerask_cp3k_mb/ auerask_cp3k_bri/ bfin_sport_tdm/
 
 # If you want to build for a kernel other than the current kernel, set KVERS
 ifndef KVERS
