--- app_flite-0.6/Makefile.orig	2009-07-08 03:48:36.000000000 +0200
+++ app_flite-0.6/Makefile	2009-07-08 04:41:40.000000000 +0200
@@ -11,33 +11,29 @@
 #  file for details.
 #
 
-AST_VER=$(shell asterisk -V | sed \
-	-e 's/Asterisk 1.2.*/2/' \
-	-e 's/Asterisk 1.4.*/4/' \
-	-e 's/Asterisk 1.6.*/6/')
-
-ASTERISKMODDIR=/usr/lib/asterisk/modules
+AST_VER=4
+ASTERISKMODDIR=/offload/asterisk/modules
 ASTERISKETCDIR=/etc/asterisk
 
 # Set ASTERISKINCLUDE and FLITEINCLUDE if you have non-standard locations for your header files
-INCLUDE=$(ASTERISKINCLUDE) $(FLITEINCLUDE)
+#INCLUDE=$(ASTERISKINCLUDE) $(FLITEINCLUDE)
 
 # Install the Flite Application
 APPS=app_flite.so
 
-CC=gcc
+#CC=gcc
 INSTALL=install
 
-OPTIMIZE=-O6
+#OPTIMIZE=-O6
 
 #Include debug symbols in the executables (-g)
-DEBUG=-g 
+#DEBUG=-g 
 
-CFLAGS+=-pipe -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations $(DEBUG) $(INCLUDE) -D_REENTRANT -D_GNU_SOURCE
-CFLAGS+=$(OPTIMIZE)
-CFLAGS+=$(shell if $(CC) -march=$(PROC) -S -o /dev/null -xc /dev/null >/dev/null 2>&1; then echo "-march=$(PROC)"; fi)
-CFLAGS+=$(shell if uname -m | grep -q ppc; then echo "-fsigned-char"; fi)
-CFLAGS+=-fPIC
+#CFLAGS+=-pipe -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations $(DEBUG) $(INCLUDE) -D_REENTRANT -D_GNU_SOURCE
+#CFLAGS+=$(OPTIMIZE)
+#CFLAGS+=$(shell if $(CC) -march=$(PROC) -S -o /dev/null -xc /dev/null >/dev/null 2>&1; then echo "-march=$(PROC)"; fi)
+#CFLAGS+=$(shell if uname -m | grep -q ppc; then echo "-fsigned-char"; fi)
+#CFLAGS+=-fPIC
 CFLAGS+=-DASTERISK_VERSION=$(AST_VER)
 
 LIBS+=-lm -lflite -lflite_cmulex -lflite_usenglish -lflite_cmu_us_kal
@@ -64,22 +60,22 @@
 
 install: all
 	@if [ -d $(ASTERISKMODDIR) ]; then \
-		for x in $(APPS); do echo $(INSTALL) -m 755 $$x $(DESTDIR)$(ASTERISKMODDIR); $(INSTALL) -m 755 $$x $(DESTDIR)$(ASTERISKMODDIR); done \
+		for x in $(APPS); do echo $(INSTALL) -m 755 $$x $(ASTERISKMODDIR); $(INSTALL) -m 755 $$x $(ASTERISKMODDIR); done \
         else \
 		echo; echo $(ASTERISKMODDIR) does not exist.; \
 		echo Please set ASTERISKMODDIR to the directory containing your Asterisk modules.; \
 		echo e.g. make install ASTERISKMODDIR=/your/directory/here; \
 		exit 1; \
 	fi
-	@if [ -d $(ASTERISKETCDIR) ]; then \
-		echo $(INSTALL) -m 644 flite.conf $(DESTDIR)$(ASTERISKETCDIR); \
-                $(INSTALL) -m 644 flite.conf $(DESTDIR)$(ASTERISKETCDIR);\
-        else \
-                echo; echo $(ASTERISKETCDIR) does not exist.; \
-                echo Please set ASTERISKETCDIR to the directory containing your Asterisk configuration files.; \
-                echo e.g. make install ASTERISKETCDIR=/your/directory/here; \
-                exit 1; \
-        fi; 
+#	@if [ -d $(ASTERISKETCDIR) ]; then \
+#		echo $(INSTALL) -m 644 flite.conf $(ASTERISKETCDIR); \
+#                $(INSTALL) -m 644 flite.conf $(ASTERISKETCDIR);\
+#        else \
+#                echo; echo $(ASTERISKETCDIR) does not exist.; \
+#                echo Please set ASTERISKETCDIR to the directory containing your Asterisk configuration files.; \
+#                echo e.g. make install ASTERISKETCDIR=/your/directory/here; \
+#                exit 1; \
+#        fi; 
 	@echo; echo Installation successful.;
 
 reload: install
