

install:
	mkdir /var/lib/asterisk/static-http/sms/
	cp prototype.js /var/lib/asterisk/static-http/sms/
	cp astman.js /var/lib/asterisk/static-http/sms/
	cp sms.html /var/lib/asterisk/static-http/sms/
clean:	
	rm /var/lib/asterisk/static-http/sms/prototype.js
	rm /var/lib/asterisk/static-http/sms/astman.js
	rm /var/lib/asterisk/static-http/sms/sms.html
	rmdir /var/lib/asterisk/static-http/sms/
