#!/bin/sh
# Must run before asterisk


echo "Starting pika-gsm driver. Please wait."
if [ -f /proc/driver/taco ] ; then
    fgrep -qi GSM /proc/driver/taco && modprobe pika-gsm
    fgrep -qi GSM /proc/driver/taco && killall syslogd
    fgrep -qi GSM /proc/driver/taco && /sbin/syslogd -L
else
    # Old taco driver
    modprobe pika-gsm
fi

# increase the maximum message queue size
echo 65536 > /proc/sys/kernel/msgmnb
